"""Translator for decoding solutions to understandable output format."""

from exact_cover_solver.types import Solution, SubsetCollection
from typing import List

PentominoBoard = List[List[str]]


class Translator:
    """Translator for decoding solutions to understandable output format."""

    @staticmethod
    def to_pentomino_boards(
        solutions: List[Solution],
        board_height: int,
        board_width: int,
        subset_collection: SubsetCollection,
    ) -> List[PentominoBoard]:
        """Convert list of solutions to pentomino boards.

        Args:
            solutions: Solutions generated by algorithm X
            board_height: Pentomino board height
            board_width: Pentomino board width
            subset_collection: Original pentomino placement possibilities
        """
        boards: List[PentominoBoard] = []
        for solution in solutions:
            print(solution)
            board: PentominoBoard = [[""] * board_width for _ in range(board_height)]
            for subset_id in solution:
                pentomino_name, *points = subset_collection[subset_id]
                for x, y in points:
                    board[y][x] = pentomino_name
            for row in board:
                print(row)
            print("")
            boards.append(board)
        return boards
