name: Code style

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7]
        poetry-version: [1.1.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry with Github actions 
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install packages with poetry
      run: |
        poetry install 
    - name: Lint with flake8 and black
      run: |
        poetry run invoke lint
