name: Tests

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
        poetry-version: [1.1.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry with Github actions 
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install packages with poetry
      run: |
        poetry install 
    - name: Run tests and report coverage
      run: |
        poetry run invoke test
    - name: Push to coveralls.io with python-coveralls
      run: |
        poetry install coveralls
        poetry run coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
